### PR TITLE
Making a sys crate

### PR DESCRIPTION
**Pull request by kornelski**
# 👉 [Rendered view of the article](https://github.com/kornelski/temp-sys-crate-post/blob/v1/making%20rust%20sys%20crate.md) 👈 

Please [review](https://github.com/kornelski/temp-sys-crate-post/pull/1/files)!

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
> Unfortunately, crates.io is not suited for distribution of binaries. Use another package manager (e.g. apt/RPM, chocolatey) to distribute a pre-compiled shared library (cdylib) and in the sys crate expect it to be pre-installed.

Ahh, so this post is mainly targeted at people creating `*-sys` crates for publishing to crates.io then? The reason I originally asked about binding to closed-source libraries is because we use some Rust at work and I've had to write bindings for 3rd party proprietary libraries in the past.

**Comment by Michael-F-Bryan** [comment]
>  Presumably you have the closed library as a .so/.dll rather than .a/.lib, so it will need to have a specific location (rpath) hardcoded in the final executable

The Windows loader will search the current directory and `$PATH` when trying to load a library, so 95% of the time everything will work by putting dependencies in the same directory as your executable. 

For proprietary stuff I think your suggestion of "manage dependency installation manually" is the most practical. It's a pain in the butt, but then that sums up most Windows programming the moment you leave Visual Studio...

**Comment by kornelski** [comment]
Ok, that's an idea I haven't considered before: you could copy the DLL to `CARGO_TARGET_DIR` and expect the executable to read it from the directory its run from. On macOS that's more involved since it requires rewriting the rpath in the library's binary, but it's still doable.

**Comment by kornelski** [comment]
Thanks everyone for reviewing it.

**Comment by kornelski** [comment]
It's posted https://kornel.ski/rust-sys-crate

**Pull request merged**
